-- MySQL Script generated by MySQL Workbench
-- Fri Aug  7 04:13:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema uams
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uams` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`category_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category_1` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`category_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category_2` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`category_3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category_3` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));

USE `uams` ;

-- -----------------------------------------------------
-- Table `uams`.`programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uams`.`programs` (
  `id` CHAR(36) NOT NULL,
  `department_id` CHAR(36) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `degree_level` VARCHAR(30) NOT NULL,
  `duration_years` DECIMAL(3,1) NOT NULL,
  `total_credits` DECIMAL(5,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uams`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uams`.`students` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `program_id` CHAR(36) NOT NULL,
  `advisor_id` CHAR(36) NULL DEFAULT NULL,
  `batch_id` CHAR(36) NULL DEFAULT NULL,
  `section_id` CHAR(36) NULL DEFAULT NULL,
  `guardian_id` CHAR(36) NULL DEFAULT NULL,
  `student_id` VARCHAR(30) NOT NULL,
  `registration_no` VARCHAR(30) NOT NULL,
  `current_semester` INT NOT NULL DEFAULT '1',
  `is_registration_cleared` TINYINT(1) NOT NULL DEFAULT '0',
  `has_received_laptop` TINYINT(1) NOT NULL DEFAULT '0',
  `status` ENUM('ACTIVE', 'DROPPED', 'GRADUATED', 'SUSPENDED') NOT NULL,
  `admitted_at` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `student_id` (`student_id` ASC) VISIBLE,
  UNIQUE INDEX `registration_no` (`registration_no` ASC) VISIBLE,
  INDEX `student_enrolled_in_program` (`program_id` ASC) VISIBLE,
  CONSTRAINT `student_enrolled_in_program`
    FOREIGN KEY (`program_id`)
    REFERENCES `uams`.`programs` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
