# Active Profile (Locally dev will run automatically)
spring.profiles.active=dev

# Application Name
spring.application.name=uams

# Server Port (Railway will override this dynamically with ${PORT})
server.port=${PORT:8080}

# JWT Configuration
jwt.secret=${JWT_SECRET:9a4f4c354565456c4a596f5a51446b4c4d5642514e57465a4a523034}
jwt.expiration=86400000

# File Upload & Post Size Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-post-size=10MB

# Custom Properties
file.upload-dir=uploads
uams.campus.code=005